# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30

# Issues with these labels will never be considered stale
exemptLabels:
  - area/security
  - bug

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale due to no recent activity for the last 60 days.

  It will be closed if no further activity occurs in the next 30 days.

  Thank you for your contributions!

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed due to no recent activity for the last 90 days.

  Thank you for your contributions!
